name: learningflutterexamples
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  backdrop: ^0.4.1
  share: ^0.6.4+3
  url_launcher: ^5.4.10
  flare_splash_screen: ^3.0.1
  autocomplete_textfield: ^1.7.3
  dropdown_search: ^0.4.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
